### ISSUE TITLE
error while watch for karma in gulp

### ISSUE THREAD

**Issue by egel** [Contactis/translations-manager#34]
The error occurs while using `gulp watch` and `gulp build`, when one of tests fail.

The console error:
![selection_004](https://cloud.githubusercontent.com/assets/3322106/11311483/698a9bd8-8fd0-11e5-9ec7-f542c87e03cf.png)

and also text version:

```
[21:39:44] 'run-karma' errored after 536 ms
[21:39:44] Error: 1
  at formatError (/home/maciej/.nvm/versions/node/v4.1.0/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/home/maciej/.nvm/versions/node/v4.1.0/lib/node_modules/gulp/bin/gulp.js:195:15)
  at emitOne (events.js:82:20)
  at Gulp.emit (events.js:169:7)
  at Gulp.Orchestrator._emitTaskDone (/home/maciej/workspace/translations-manager/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /home/maciej/workspace/translations-manager/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/home/maciej/workspace/translations-manager/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/home/maciej/workspace/translations-manager/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at removeAllListeners (/home/maciej/workspace/translations-manager/node_modules/karma/lib/server.js:332:7)
  at Server.<anonymous> (/home/maciej/workspace/translations-manager/node_modules/karma/lib/server.js:343:9)
  at Server.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Server.emit (events.js:166:7)
  at emitCloseNT (net.js:1518:8)
  at doNTCallback1 (node.js:418:9)
  at process._tickDomainCallback (node.js:381:17)
  at process.<anonymous> (/home/maciej/workspace/translations-manager/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)
```

**Comment by egel** [comment]
resolved with b2949ac5690245fe2f094ccdeae880684f3bd9ca
